name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    if: ${{ !startsWith(github.event.head_commit.message, 'v') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm prettier:check-all
      - name: Lint
        run: pnpm eslint:lint-all
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
